version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db-mysql-note-sharing-do-user-17066697-0.c.db.ondigitalocean.com:25060/defaultdb
      DB_USERNAME: doadmin
      DB_PASSWORD: AVNS_tdjUWzpWRbQ7dnu9xN3
